---
abstract: "Perl extension to OpenSSL's PKCS10 API."
author:
  - 'JoNO <jonozzz@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test: '0'
configure_requires:
  Crypt::OpenSSL::Guess: '0.11'
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-OpenSSL-PKCS10
no_index:
  directory:
    - t
    - inc
recommends:
  Crypt::OpenSSL::Bignum: '0'
requires:
  Crypt::OpenSSL::RSA: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Crypt-OpenSSL-PKCS10
  repository: git@github.com:perl-net-saml2/perl-Crypt-OpenSSL-PKCS10.git
  homepage: https://metacpan.org/pod/Crypt::OpenSSL::PKCS10
  license: http://dev.perl.org/licenses/
version: '0.20'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
